spring:
  application:
    name: notification-service
  config:
<<<<<<< HEAD
    import: optional:configserver:http://config-server:8888
=======
    import: optional:configserver:http://localhost:8888
  
>>>>>>> db6409ff3d530454665e452848781b122316a7f4
